export const PUBLIC_KEY = `
  -----BEGIN PUBLIC KEY-----
  MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/BXzzFpKUQKp2OWP11OQiUhTl
  9a21I5bSP4N7ydCiuXQRd7fIVkavFF1HjFpwdjM6RACjl7AulyQt/wQfnaVP19H3
  KkXDIFZPBkQx2qjef6dw7VZhiexruXerdkBD9IVffrRN2QhuriLZpT/yc3iQYd/i
  4CEzf4GwIRxMA+2xswIDAQAB
  -----END PUBLIC KEY-----`
